Update parallel-training.md
deepmodeling/deepmd-kit pull request #1156
Opened 2021-09-15 21:23 UTC by chazeon

Add additional information for parallel training documentation.

2021-09-16 00:21 UTC, amcadmus commented
The environment setup part has been moved to the installation doc #1147 do you mind moving the check-build part of your revise to the installation?

2021-09-16 00:57 UTC, njzjz requested changes

2021-09-16 00:57 UTC, njzjz commented on doc/train/parallel-training.md
> +What's more, 2 command-line arguments are defined to control the logging behvaior when performing performing parallel training with MPI.
Duplicated word "performing"

2021-09-16 03:28 UTC, chazeon commented on doc/train/parallel-training.md
> +What's more, 2 command-line arguments are defined to control the logging behvaior when performing performing parallel training with MPI.
Addressed in latest commit.

2021-09-16 10:48 UTC, njzjz approved these changes

2021-09-17 01:32 UTC, shishaochen approved these changes

2021-09-17 06:25 UTC, merged