fix bug of mixed precision training
deepmodeling/deepmd-kit pull request #1471
Opened 2022-02-11 03:36 UTC by denghuilu

#1469 should be fixed by this PR.

2022-02-11 06:00 UTC, wanghan-iapcm reviewed
Do wen have similar issues in other descriptors?

2022-02-11 06:12 UTC, denghuilu commented
> Do wen have similar issues in other descriptors?

No, only `se_a` type support the mixed precision training.

2022-02-11 21:53 UTC, njzjz requested changes

2022-02-11 21:53 UTC, njzjz commented on deepmd/descriptor/se_a.py
> +          xyz_scatter = tf.cast(tf.reshape(xyz_scatter, (-1, shape_i[1]//4, outputs_size[-1])), self.filter_precision)
If I understand correctly, it causes the error that [`deepmd.utils.network.embedding_net`](https://github.com/deepmodeling/deepmd-kit/blob/82c787de0ea98e3c032368a5fd4ee46a1fac6283/deepmd/utils/network.py#L99) accepts an input with `self.filter_precision` precision but returns one with `self.mixed_prec`. It is inconsistent. You should both cast and cast back inside the `embedding_net` or outside that method, but do not cast inside the `embedding_net` and cast back here.

2022-02-14 02:54 UTC, wanghan-iapcm commented on deepmd/utils/network.py
> -                return hidden
why the case `activation_fn == None` is removed?

2022-02-14 03:03 UTC, njzjz approved these changes

2022-02-15 07:54 UTC, merged