support custom gelu implementation
deepmodeling/deepmd-kit pull request #1795
Opened 2022-06-28 15:20 UTC by denghuilu

2022-06-28 15:22 UTC, denghuilu commented
#1621 should be fixed

2022-06-28 19:18 UTC, njzjz requested changes

2022-06-28 19:18 UTC, njzjz commented on doc/train-input-auto.rst
> +            The activation function in the embedding net. Supported activation functions are "relu", "relu6", "softplus", "sigmoid", "tanh", "gelu", "gelu_tf". Note that "gelu" denotes the custom ope
The documentation should be add to `argcheck.py`

2022-06-28 19:18 UTC, njzjz commented on deepmd/common.py
> +    `x` with the GELU activation applied
document the type
```suggestion
    tf.Tensor
        `x` with the GELU activation applied
```

2022-06-29 02:51 UTC, njzjz approved these changes

2022-06-29 05:22 UTC, merged