Upload attention based model
deepmodeling/deepmd-kit pull request #1866
Opened 2022-08-19 17:00 UTC by iProzd

Here I upload the implementation of attention based model (DPA-1), see details in paper: https://arxiv.org/abs/2208.08236.
The changes can mainly be listed as following:
1. Add a new descriptor '**se_atten**', using attention schemes and type embeddings (deepmd/descriptor/se_atten.py);
2. Add a new custom op '**ProdEnvMatAMix**', mixing atoms with different types in the sorting, which is only suitable for descriptor using type embeddings (source/op/prod_env_mat_multi_device.cc and other sub files, here I try the best to reuse the previous codes);  
3. Other changes to match the newly added descriptor, such as 'sel' supporting 'int' type as input (deepmd/entrypoints/train.py ) and type embedding with padding (deepmd/utils/type_embed.py);
4. **Large_batch_mode**: a new format of DeepmdData  to put different systems sharing the same 'nloc' (instead of same fingerprints) together. (deepmd/utils/data.py & data_system.py) Note that this is only the training code on this new format of data. The generation code of this new format will soon be uploaded in _dpdata_.
5. An example of DPA-1 on water system (examples/water/se_atten/input.json);
6. The unittests on both C++&CUDA&ROCM and python interface of newly added apis(source/lib/tests & source/tests).

2022-08-19 17:08 UTC, iProzd commented
@amcadmus @njzjz

2022-08-19 19:46 UTC, njzjz requested changes
This is a preliminary review.

Besides, there is no documentation to describe it.

2022-08-19 19:46 UTC, njzjz commented on source/lib/src/prod_env_mat.cc
> +  memset(rij, 0.0, sizeof(FPTYPE) * nloc * nnei * 3);
The second parameter of `memset` is passed as an `int`. See https://cplusplus.com/reference/cstring/memset/

2022-08-19 19:46 UTC, njzjz commented on deepmd/entrypoints/train.py
>          jdata = update_sel(jdata)
I see se_atten is excluded, but why not first update_sel and then make the sum?

2022-08-19 19:46 UTC, njzjz commented on source/lib/src/neighbor_list.cc
> +          nmask[nlist_idx]=1.;
```
(FPTYPE)1.
```

2022-08-19 19:46 UTC, njzjz commented on source/lib/src/neighbor_list.cc
> +          nmask[nlist_idx]=1.;
If only 1. and 0. are supported, why not use `bool`? It should use less memory.

2022-08-19 19:46 UTC, njzjz commented on examples/water/se_atten/input.json
> +{
Please add this file to [test_examples.py](https://github.com/deepmodeling/deepmd-kit/blob/c31b2835f677094431b3a630cd93c889e2d41f64/source/tests/test_examples.py).

2022-08-19 19:46 UTC, njzjz commented on deepmd/descriptor/se_atten.py
> +            Only for the purpose of backward compatibility, retrieves the old behavior of using the random seed
Some parameters are missing.

2022-08-19 19:46 UTC, njzjz commented on deepmd/fit/ener.py
> +                             large_batch_mode: bool = False
The new parameter was not added to the docstring.

2022-08-19 19:46 UTC, njzjz commented on deepmd/utils/data.py
> +        return large_batch_mode
These four lines can be written as one line:
```py
return os.path.isfile(os.path.join(sys_path, 'set.000', 'real_atom_types.npy'))
```

2022-08-20 00:48 UTC, njzjz commented on deepmd/utils/data.py
> +        return large_batch_mode
Besides, use DPPath class

2022-08-20 04:17 UTC, wanghan-iapcm requested changes
- The organization and the data format of the DPA model is different from the standard DP model. We should explain in the doc what is the difference and how to prepare data.

2022-08-20 04:17 UTC, wanghan-iapcm commented on source/lib/src/prod_env_mat.cc
> +prod_env_mat_a_mix_cpu(
We should be able to implement it within `prod_env_mat_a_cpu`. 

Adding one parameter `const int * f_type` with default value `type` to `prod_env_mat_a_cpu` would work.

2022-08-20 04:17 UTC, wanghan-iapcm commented on source/lib/src/prod_env_mat.cc
> +prod_env_mat_a_mix_cpu(
The same comment for the cuda and rocm variances  of `prod_env_mat`

2022-08-20 04:17 UTC, wanghan-iapcm commented on source/op/prod_env_mat_multi_device.cc
> +    _map_nei_info_cpu(nlist, ntype, nmask, type, &idx_mapping[0], nloc, nnei, ntypes, b_nlist_map);
have you mapped the neighbor index when the coords are copied?

2022-08-21 03:26 UTC, wanghan-iapcm requested changes

2022-08-21 03:26 UTC, wanghan-iapcm commented on doc/model/train-se-atten.md
> +An ideal way is to put systems with same total number of atoms together, which is the way we trained DPA-1 on OC2M. This API will be uploaded on dpdata soon for a more convenient experience.
You should explain, in detail, how one prepares the training data for DPA-1. Someone may want to manually prepare data, rather than using dpdata.

2022-08-21 04:18 UTC, njzjz commented on doc/model/train-se-atten.md
> +DPA-1 will be merged into DeePMD-kit official repo: [github](https://github.com/deepmodeling/deepmd-kit), and before that, for early adopters, you can refer to the following steps for a quick start:
This should not be merged

2022-08-21 04:18 UTC, njzjz commented on deepmd/fit/ener.py
> +            self.tmp_input = inputs
What is it used for?

2022-08-23 17:06 UTC, njzjz commented
Depth of TOC is wrong:
![image](https://user-images.githubusercontent.com/9496702/186220378-bcb8c957-b414-4858-ba54-826457734510.png)

2022-08-23 23:21 UTC, njzjz commented on deepmd/utils/network.py
> +        if activation_fn != None:
Please use `is not None`. See https://peps.python.org/pep-0008/#programming-recommendations

2022-08-23 23:21 UTC, njzjz commented on source/op/prod_env_mat_multi_device.cc
> +    .Output("nmask: T");;
Maybe you could add a summary to the new OP, especially the difference from the old OP.

```cpp
.Doc(R"(Something

something something
something.)");
```

2022-08-23 23:21 UTC, njzjz commented on deepmd/utils/argcheck.py
> +    doc_activation_function = f'The activation function in the embedding net. Supported activation functions are {list_to_doc(ACTIVATION_FN_DICT.keys())}. Note that "gelu" denotes the custom operator
Duplicated period.
![image](https://user-images.githubusercontent.com/9496702/186282298-9dfe95c3-8f07-4769-af45-f8ca6b182147.png)

2022-08-24 11:35 UTC, wanghan-iapcm requested changes

2022-08-24 11:35 UTC, wanghan-iapcm commented on deepmd/utils/type_embed.py
> +            self.filter_activation_fn = get_activation_func(activation_function)
revise `get_activation_function` to allow the input being "none" and None?

2022-08-24 11:35 UTC, wanghan-iapcm commented on deepmd/train/trainer.py
> +                neuron=[8],
Why the `neuron` is hard coded?

2022-08-24 11:35 UTC, wanghan-iapcm commented on doc/model/train-se-atten.md
> +type_number| Number of atoms in each type     | real_atom_numbs.npy | Required             | Nframes \* Ntypes        | Integers that describe the totoal number of atoms with the same type in each fr
I do not see where do you implement the IDs `fake_type`, `real_type` and `type_number`. The ID means the keys in the data_dict of DeepmdData.

2022-08-24 11:35 UTC, wanghan-iapcm commented on deepmd/utils/data.py
> +            data['real_natoms_vec'] = np.concatenate((np.tile(np.array([natoms, natoms], dtype=np.int32), (nframes, 1)),
Should not the `real_natom_vec` be calculated from `real_atom_types`?

2022-08-24 11:35 UTC, wanghan-iapcm commented on deepmd/utils/data_system.py
> +                assert data_sys.mixed_type, "all systems must have the same format for mixed_type!"
The error message is not clear... 
"if one of the system is of mixed_type, then all of the systems should be of mixed_type"

But, the check is only triggered when the data_system[0] is mixed_type. Suppose the case data_system[0] is normal system and data_system[1] is mixed_type, the current check cannot catch the case. 

We should raise error if **ANY** of the data_system is mixed_type and at least one of them is not.

2022-08-24 11:35 UTC, wanghan-iapcm commented on source/tests/common.py
> +                  seed = 1,
Please do not introduce format editing in this PR.

2022-08-25 00:56 UTC, njzjz commented on deepmd/common.py
> +        return None
You can return `lambda x: x` for None, and this will not be a special case but have the same behavior as other activation functions.

2022-08-25 00:56 UTC, njzjz commented on deepmd/entrypoints/train.py
>          jdata = update_sel(jdata)
This is not resolved

2022-08-25 16:06 UTC, njzjz commented on deepmd/utils/argcheck.py
> +        Argument("activation_function", str, optional = True, default = None, doc = doc_activation_function),
This is a breaking change! We should not introduce it.

2022-08-25 17:09 UTC, njzjz approved these changes

2022-08-26 02:49 UTC, wanghan-iapcm approved these changes

2022-08-26 02:49 UTC, merged