Support multiple sets in one system for mixed_type format
deepmodeling/deepmd-kit pull request #2343
Opened 2023-02-24 18:19 UTC by iProzd

2023-02-24 19:31 UTC, njzjz requested changes

2023-02-24 19:31 UTC, njzjz commented on deepmd/utils/data.py
> +            self.mixed_type = False
Here two conditions can be merged
```suggestion
        self.mixed_type = self._check_mode(self.dirs[0]):
        for set_item in self.dirs[1:]:
            assert self._check_mode(set_item) == self.mixed_type, error_format_msg
```

2023-02-24 19:31 UTC, njzjz commented on deepmd/utils/data.py
> +                except RuntimeError as e:
Isn't it `IndexError`?

2023-02-25 09:23 UTC, njzjz commented
Please remove "Note that we put all the frames in one set set.000" from the documentation.

2023-02-25 14:34 UTC, wanghan-iapcm approved these changes

2023-02-25 14:44 UTC, njzjz approved these changes

2023-02-25 14:44 UTC, merged