Fix dplr error
deepmodeling/deepmd-kit pull request #2436
Opened 2023-04-01 01:33 UTC by Yi-FanLi

DPLR is broken due to the change of coeff(int narg, char **arg) function. The current coeff function requires that the number of types in LAMMPS no more than that in model. In dplr, however, there might be more types in LAMMPS than in the model. This check should be bypassed.

2023-04-01 08:22 UTC, njzjz submitted a review, later dismissed
Approve, although I hope a test

2023-04-01 18:01 UTC, Yi-FanLi commented
I added a test. However, I am not able to set up the pytest environment on my local computer right now. I pushed the test to this branch, and let's see how github actions perform on this test.

2023-04-01 23:40 UTC, njzjz commented
I add `select_real_atoms` to model deviation in https://github.com/Yi-FanLi/deepmd-kit/pull/2. It seems to me that the model deviation never works for DPLR?

2023-04-02 01:32 UTC, njzjz approved these changes
Ok, the tests have passed

2023-04-03 05:52 UTC, wanghan-iapcm requested changes

2023-04-03 05:52 UTC, wanghan-iapcm commented on source/lmp/tests/data_type_map2.lmp
Please do not commit the data file. write one by the setUp of your test, then remove the file at tearDown.

2023-04-03 05:52 UTC, wanghan-iapcm commented on source/lmp/tests/data2.lmp
Please do not commit the data file. write one by the setUp of your test, then remove the file at tearDown.

2023-04-03 05:52 UTC, wanghan-iapcm commented on source/api_cc/src/DeepPot.cc
> +                          nall - nghost);
The selection of real atoms looks similar across different `compute` methods. Could you please pack them in one function and call from the `compute`s the function?

2023-04-17 04:03 UTC, wanghan-iapcm approved these changes

2023-04-17 04:31 UTC, merged