support the DOS (electronic density of states) fitting
deepmodeling/deepmd-kit pull request #2449
Opened 2023-04-09 12:30 UTC by mingzhong15

here i present the implementation of DeepDOS model [Phys. Rev. B 105, 174109 (2022)] in dpkit-devel branch

generally, i add a new `fitting_type = 'dos'` to allow the DP to fit a vector. this vector can be global (`dos.raw/npy`) or atomic (`atom_dos.raw/npy`), whose length is `numb_dos`.

specifically, 
1. `fit/dos.py`, `loss/dos.py`, `model/dos.py` and `infer/deep_dos.py` is created to allow fitting and inference
2. relevant `*/__init__.py`, `train/trainer.py`, `utils/argcheck.py` is updated
3. in `entrypoint/freeze.py`, `entrypoint/test.py` , relevant functions are added to freeze and test the DeepDOS model
4. a simple user guide is added in the `doc/model/train-fitting-dos.md`
5. an example is provide in the `examples/dos/`, the input script is provided in the `examples/dos/train/input.json`, data sets are provided in the `examples/dos/data/`

2023-04-09 19:09 UTC, njzjz commented
pre-commit.ci autofix

2023-04-10 03:50 UTC, wanghan-iapcm requested changes
1. Please add UTs for your contributions. Thanks!
2. The data in the example are for the demonstrative purposes. Currently they are too large (~600KB) to be included in the source code. Please reduce the size of the data.

2023-04-10 19:20 UTC, njzjz requested changes

2023-04-10 19:20 UTC, njzjz commented on doc/model/train-fitting-dos.md
> +# Fit `DOS`
The full name of DOS should be used in the title, as only some people know it.

2023-04-10 19:20 UTC, njzjz commented on examples/dos/train/test.sh
This file is not useful

2023-04-10 19:20 UTC, njzjz commented on deepmd/fit/dos.py
> +        #        .add("trainable",        [list, bool], default = True)
please clean useless comments

2023-04-10 19:20 UTC, njzjz commented on deepmd/utils/argcheck.py
> +        Argument("ener_max", float, optional=True, default=10.0, doc=doc_ener_max),
Is it a good idea to give a default value?

2023-04-11 00:04 UTC, mingzhong15 commented
thank you for the advice, i will revise the code. Also, i will add unit tests

2023-04-12 05:55 UTC, wanghan-iapcm approved these changes

2023-04-12 18:03 UTC, njzjz commented
> Patch coverage: **`27.76`**% and project coverage change: **`-1.59`** ⚠️

Please note that only 27.76% of the new codes have been tested.

2023-04-13 18:33 UTC, njzjz approved these changes
@wanghan-iapcm is it ok to merge? Indeed there are still some codes that are not covered.

2023-04-15 01:28 UTC, merged

2023-04-15 01:30 UTC, wanghan-iapcm commented
> @wanghan-iapcm is it ok to merge? Indeed there are still some codes that are not covered.

sry i did not notice your comment.