Add zbl example
deepmodeling/deepmd-kit pull request #2613
Opened 2023-06-13 08:44 UTC by Chengqian-Zhang

I add the example of using zbl in training process.

2023-06-13 15:40 UTC, njzjz requested changes

2023-06-13 15:40 UTC, njzjz commented on examples/water/zbl/input.json
This file should be added to `source/tests/test_examples.py` to ensure the parameters are always correct.

2023-06-25 03:30 UTC, Chengqian-Zhang commented on examples/water/zbl/input.json
I have done it. Please check.

2023-06-25 07:34 UTC, wanghan-iapcm approved these changes

2023-06-25 14:29 UTC, njzjz approved these changes

2023-06-26 00:43 UTC, merged