add citation for `aparam`
deepmodeling/deepmd-kit pull request #2825
Opened 2023-09-15 11:58 UTC by mingzhong15

add reference for `aparam`

2023-09-15 16:11 UTC, njzjz requested changes

2023-09-17 02:13 UTC, mingzhong15 commented on CITATIONS.bib
> +@article{Zeng_2023_TTMDPMD,
should i delete the citation in the `credits.rst`  ?

2023-09-17 03:24 UTC, njzjz commented on CITATIONS.bib
> +@article{Zeng_2023_TTMDPMD,
![image](https://github.com/deepmodeling/deepmd-kit/assets/9496702/3e22f68d-8232-4087-9cc2-c9984e4c78c2)

After changing `@article` to `@misc`, the current one should be okay. Although `arXiv` is not shown, it's better than nothing.

2023-09-17 03:25 UTC, njzjz approved these changes

2023-09-18 03:45 UTC, merged