Update Data.py
deepmodeling/deepmd-kit pull request #290
Opened 2020-11-09 06:43 UTC by bwang-ecnu

When condition “if coeff_atom_ener==1:” is established and one would like to ignore the energy_file, it seems to need to replace "coeff_atom_ener=1" with "coeff_ener=0".

2020-11-09 13:52 UTC, njzjz approved these changes

2020-11-13 02:03 UTC, amcadmus requested changes
Shouldn't it be coeff_ener = 1? 
at line 478 the system energy is computed by reducing the atomic energies. thus we have the system energy label.

2020-11-13 09:36 UTC, amcadmus approved these changes

2020-11-15 23:47 UTC, merged

2020-11-17 22:07 UTC, njzjz commented
This PR was merged into master...