fix: make the se attn v2 descriptor energy conservative.
deepmodeling/deepmd-kit pull request #2905
Opened 2023-10-09 11:31 UTC by wanghan-iapcm

This PR fixes issue #2811
1. fix the auto-diff issue: input should be `descriptor_reshape`. 
2. fix the discontinuity introduced in the attention map.

2023-10-09 20:19 UTC, njzjz requested changes
It seems to be a critical bug that the energy does not match the force. Do we need to add it to #2866?

2023-10-09 20:19 UTC, njzjz commented on deepmd/descriptor/se_atten.py
To my understanding, the current compression kernel assumes the gradient of two_embed (`dy_dtwo`) is zero, so the forces will be incorrect when `dy_dtwo` is not zero.
Previously, due to this bug, `dy_dtwo` of the uncompressed model is also zero.
Luckily, it's caught by an indirect unit test...

2023-10-09 21:56 UTC, njzjz commented on deepmd/descriptor/se_atten.py
I've done the `grad`. Need to check `gradgrad`.

2023-10-10 00:12 UTC, njzjz commented on source/lib/tests/test_tabulate_se_a.cc
> +      dy_dem_x_dev, dy_dem_dev, dy_dtwo, table_dev, &info[0], em_x_dev, em_dev,
```suggestion
      dy_dem_x_dev, dy_dem_dev, dy_dtwo_dev, table_dev, &info[0], em_x_dev, em_dev,
```

2023-10-10 00:14 UTC, njzjz commented on deepmd/descriptor/se_atten.py
Need help for gradgrad

2023-10-10 03:48 UTC, njzjz commented on deepmd/descriptor/se_atten.py
`gradgrad` done

2023-10-10 18:13 UTC, iProzd approved these changes

2023-10-10 19:57 UTC, njzjz approved these changes

2023-10-11 01:40 UTC, nahso approved these changes

2023-10-11 01:42 UTC, nahso commented on source/lib/src/gpu/tabulate.cu
> +    DPErrcheck(gpuMemset(dy_dtwo, 0, sizeof(FPTYPE) * nloc * nnei));
This `memset` can be removed since all elements in `dy_dtwo` will be modified later, so the parameter of memory size is unimportant.

2023-10-11 02:35 UTC, merged