add cosine restart learning rate
deepmodeling/deepmd-kit pull request #2953
Opened 2023-10-27 10:17 UTC by hellozhaoming

2023-10-27 13:00 UTC, wanghan-iapcm commented on deepmd/utils/learning_rate.py
> +    def value(self, step: int) -> float:
you may not need to implement the value method if you do not print the information regarding the learning rate at the beginning of the training:
https://github.com/hellozhaoming/deepmd-kit/blob/05052c195308f61b63ce2bab130ce0e8cba60604/deepmd/train/trainer.py#L566

2023-10-27 19:46 UTC, njzjz requested changes
Please run `pre-commit` to format and lint the code: https://docs.deepmodeling.com/projects/deepmd/en/master/development/coding-conventions.html#run-scripts-to-check-the-code. Or you can submit from a non-protect branch and pre-commit.ci can do it for you.

Unit tests should be added for two new learning rate classes.

2023-10-27 19:46 UTC, njzjz commented on deepmd/common.py
> +    "swish": tf.nn.swish,
It seems that it has been renamed to `silu`: https://github.com/tensorflow/tensorflow/issues/41066

2023-10-27 19:46 UTC, njzjz commented on deepmd/train/trainer.py
> +            if self.lr_type == "exp":
It's not a good behavior to switch the learning rate in the `Trainer`. Instead, implement the method `LearningRate.log_start` (`LearningRate` should be an abstract base class and inherited by all learning rate classes) and call `self.lr.log_start(self.sess)` here.

2023-10-27 19:46 UTC, njzjz commented on deepmd/utils/argcheck.py
> +         Argument("cosrestart", dict, learning_rate_cosrestarts())],
You may need to add some documentation to variants (`doc="xxx"`). Otherwise, no one knows what they are.

2023-10-27 19:46 UTC, njzjz commented on deepmd/utils/learning_rate.py
> +  ```
Please use this style: https://numpydoc.readthedocs.io/en/latest/format.html#other-points-to-keep-in-mind

2023-10-27 19:46 UTC, njzjz commented on deepmd/utils/learning_rate.py
> +  ```
This line should be removed.

2026-03-02 13:30 UTC, njzjz commented
The feature has been implemented by #5142 and #5154.

2026-03-02 13:30 UTC, closed without merging