cc: add torch backend support for Multiple backend
deepmodeling/deepmd-kit pull request #3162
Opened 2024-01-22 10:43 UTC by CaRoLZhangxy

need to test in union environment (tf and pt)
see https://github.com/deepmodeling/deepmd-kit/issues/3119

2024-01-23 03:58 UTC, njzjz requested changes

2024-01-23 03:58 UTC, njzjz commented on source/api_cc/src/DeepPotPT.cc
> +  torch::Device device(torch::kCUDA, gpu_rank);
What happens when the GPU is not available?

2024-01-23 03:58 UTC, njzjz commented on source/api_cc/src/DeepPotPT.cc
> +  throw;
Always throw `deepmd::deepmd_exception`, which can be caught by the downstream software (e.g., LAMMPS).

2024-01-23 03:58 UTC, njzjz commented on source/api_cc/include/DeepPotPT.h
> +    return ntypes;
These variables (`ntypes`, `ntypes_spin`, `dim_fparam`, `dim_aparam`, `aparam_nall`) seem not to be initiated anywhere, so it's expected to see a segmentation fault.

2024-02-03 08:05 UTC, njzjz commented on source/api_cc/src/commonPT.cc
> +  jlist = (int*)malloc(inum * max_num_neighbors * sizeof(int));
Doesn't it cause the memory leaking since it is never freed?

2024-02-03 09:38 UTC, njzjz commented on source/api_cc/src/DeepPotPT.cc
> +  torch::Device device(torch::kCUDA, gpu_rank);
We may use `torch::cuda::is_available` to check here.

2024-02-05 08:49 UTC, njzjz commented on deepmd/pt/model/model/dp_atomic_model.py
> +    def get_nnei(self) -> List[int]:
Perhaps [`torch.jit.export`](https://pytorch.org/docs/stable/jit.html#torch.jit.export) should be used?

2024-02-28 00:10 UTC, njzjz requested changes

2024-02-28 00:10 UTC, njzjz commented on source/api_cc/src/commonPT.cc
> +  memset(&jlist[0], -1, nlist_size * sizeof(int));
It seems wrong: https://stackoverflow.com/a/20951450/9567349

2024-02-28 06:54 UTC, njzjz approved these changes
fparam and apraram are not supported yet. But I think it's okay for this PR.

2024-02-28 07:02 UTC, wanghan-iapcm requested changes

2024-02-28 07:02 UTC, wanghan-iapcm commented on source/api_cc/src/DeepPotPT.cc
> +//     const int& ago);
```suggestion

```

2024-02-28 07:02 UTC, wanghan-iapcm commented on source/api_cc/src/DeepPotPT.cc
> +//     const std::vector<float>& box);
```suggestion

```

2024-02-28 07:33 UTC, wanghan-iapcm approved these changes

2024-02-28 08:55 UTC, merged