Remove data stat from model init
deepmodeling/deepmd-kit pull request #3233
Opened 2024-02-05 12:01 UTC by iProzd

2024-02-06 01:07 UTC, wanghan-iapcm requested changes

2024-02-06 01:07 UTC, wanghan-iapcm commented on deepmd/pt/model/descriptor/descriptor.py
> +        """Get the keys for the data preprocess."""
one would not understand the method from such a doc str.

2024-02-06 01:07 UTC, wanghan-iapcm commented on deepmd/pt/model/descriptor/descriptor.py
> +        """Get the keys for the data statistic of the descriptor."""
one would not understand the method from such a doc str.

2024-02-06 01:07 UTC, wanghan-iapcm commented on deepmd/pt/model/model/model.py
> +            sumr, suma, sumn, sumr2, suma2 = self.descriptor.compute_input_stats(
not all the models have the data member `self.descriptor`, e.g. the pair_table atomic model. 
we should mv the method out of the base model. 

The same is for fitting. but not that the atomic_model may need the output stat.

2024-02-06 01:07 UTC, wanghan-iapcm commented on deepmd/pt/model/model/model.py
you have a lot of changes on the file. please tell what have you done

2024-02-07 10:46 UTC, closed without merging

2024-02-07 10:47 UTC, iProzd commented
See #3245 for further information.