Feat: add polarizability fitting net
deepmodeling/deepmd-kit pull request #3296
Opened 2024-02-19 02:59 UTC by anyangml

2024-02-19 03:03 UTC, wanghan-iapcm commented
#3289 will be merged before this PR.

2024-02-19 10:05 UTC, njzjz requested changes

2024-02-19 10:12 UTC, anyangml commented on deepmd/pt/model/task/fitting.py
> +                if hasattr(self, "scale"):
the alternative would be pass those parameters into the parent class. However, these parameters are specific to polar fitting. We would have to define those parameters out side of the super()__init__() in sibling classes.

2024-02-19 10:24 UTC, njzjz commented on deepmd/pt/model/task/fitting.py
> +                if hasattr(self, "scale"):
I don't see the necessity to multiply scale in the parent class.

2024-02-19 10:32 UTC, njzjz commented on deepmd/pt/model/task/fitting.py
> +                if hasattr(self, "scale"):
The multiplication can be implemented in the child class.

2024-02-19 10:35 UTC, anyangml commented on deepmd/pt/model/task/fitting.py
> +                if hasattr(self, "scale"):
I think leave it in the parent class might be better, since `dipole` may also use it.

2024-02-19 14:12 UTC, wanghan-iapcm requested changes

2024-02-20 01:38 UTC, anyangml commented on deepmd/dpmodel/fitting/polarizability_fitting.py
> +            out = np.stack([np.diag(v) for v in out])  # (nframes * nloc, m1, m1)
please take a closer look at the new implementation. It seems that it's not consistent with the old one.

2024-02-20 01:51 UTC, njzjz approved these changes

2024-02-20 02:09 UTC, wanghan-iapcm commented on deepmd/dpmodel/fitting/polarizability_fitting.py
> +            out = np.stack([np.diag(v) for v in out])  # (nframes * nloc, m1, m1)
Could you plz explain why they are not consistent?

2024-02-20 02:34 UTC, wanghan-iapcm approved these changes

2024-02-20 04:21 UTC, merged