ut: add null test
deepmodeling/deepmd-kit pull request #3391
Opened 2024-03-02 15:08 UTC by wanghan-iapcm

test the cases: 
1. system only has one atom
2. system has two atoms that are far away from each other. 

In each cases, the force and virial predictions should be zero and energy should be a valid float.

2024-03-02 15:35 UTC, njzjz approved these changes

2024-03-02 23:23 UTC, njzjz requested changes

2024-03-02 23:23 UTC, njzjz commented on source/tests/pt/model/test_null_input.py
I got the following error:
```
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelSeA::test_nloc_1 - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelSeA::test_nloc_2_far - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelDPA1::test_nloc_1 - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelDPA1::test_nloc_2_far - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelDPA2::test_nloc_1 - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestEnergyModelDPA2::test_nloc_2_far - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestForceModelDPA2::test_nloc_1 - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
FAILED source/tests/pt/model/test_null_input.py::TestForceModelDPA2::test_nloc_2_far - RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
```

2024-03-03 03:17 UTC, njzjz approved these changes

2024-03-03 03:19 UTC, anyangml approved these changes

2024-03-03 04:19 UTC, merged