docs: Replace quick_start.ipynb with a new version.
deepmodeling/deepmd-kit pull request #3567
Opened 2024-03-19 12:34 UTC by Mancn-Xu

Replace quick_start.ipynb with a new version. Aligned English tutorial with Chinese version(https://nb.bohrium.dp.tech/detail/3313403083) in structure and content.

2024-03-19 20:33 UTC, njzjz requested changes

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "1. https://docs.deepmodeling.com/projects/deepmd/en/master/index.html\n",
We don't need the reference considering it has already been in the documentation

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +      "Performance: 9.796 ns/day, 2.450 hours/ns, 113.378 timesteps/s, 566.888 atom-step/s\n",
Why does the performance degrade?

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "In an environment with a compatibable version of LAMMPS, the deep potential molecular dynamics can be performed via \n",
This change seems wrong. Need to recover.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "Here `conf.lmp` gives the initial configuration of a gas phase methane MD simulation, and the file `in.lammps` is the lammps input script. One may check in.lammps and finds that it is a rather s
This change seems wrong.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "More detailed docs about Data conversion can be found [here](https://docs.deepmodeling.org/projects/deepmd/en/master/data/data-conv.html)"
We should use the relative links in the documentation without the hard-coded branch. The original one is correct.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "! cd DeePMD-kit_Tutorial/01.train/ && cat input.json"
We may use the [new dargs feature](https://docs.deepmodeling.com/projects/dargs/en/latest/nb.html) to show the script.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "More detailed documentation on using dpdata for data conversion can be found [here](https://docs.deepmodeling.org/projects/deepmd/en/master/data/data-conv.html)"
Should not use absolute links.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "For more detailed usage, you can refer to the [DeePMD-kit’s documentation](https://docs.deepmodeling.org/projects/deepmd/en/master/index.html) as a comprehensive reference.\n",
The notebook has already been in the documentation.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "* [Background](#background)\n",
These links seem not working: https://deepmodeling--3567.org.readthedocs.build/projects/deepmd/en/3567/getting-started/quick_start.html#data-preparation

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "### 3 Train a model  <a id ='train'></a>\n",
The number here seems conflicting with that generated by Sphinx.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "In this case, the Deep Potential (DP) model was generated using the **DeePMD-kit package (v2.2.1)**.\n",
It seems no more v2.2.1. Or perhaps we should not pin the version.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +      "Performance: 9.796 ns/day, 2.450 hours/ns, 113.378 timesteps/s, 566.888 atom-step/s\n",
I see. It seems you used a CPU instead of a GPU...

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
While the original tutorial is not mentioned, could you add `dp compress` to the tutorial?

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "       This document can be executed directly on the <a style=\"font-weight:bold; color:rgb(85, 91, 228)\" href=\"https://bohrium-doc.dp.tech/docs/userguide/Notebook\" target=\"_blank\"> Bohrium
There is no "connect" button when shown in the documentation.

2024-03-19 20:33 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
Please resolve conflicts.

2024-03-27 06:15 UTC, njzjz reviewed
I still found two problems:

2024-03-27 06:15 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
When I clicked these links, nothing happened.

![image](https://github.com/deepmodeling/deepmd-kit/assets/9496702/68752e2c-c51a-4a5d-a6be-f37eb52bb965)

2024-03-27 06:15 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
Another problem is that `2.4.1` and `1` are duplicated.

![image](https://github.com/deepmodeling/deepmd-kit/assets/9496702/82113e4c-4c2b-492d-a110-f69ea1b6598b)

2024-03-27 06:18 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
May need to follow https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html

2024-03-27 06:55 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
I found it can be automatically generated instead:
https://myst-parser.readthedocs.io/en/latest/syntax/organising_content.html#document-structure

2024-03-27 17:20 UTC, njzjz approved these changes

2024-03-29 09:27 UTC, anyangml commented on doc/getting-started/quick_start.ipynb
> +    "### Run MD with LAMMPS\n",
there is a figure before 2.3.7, maybe rotate the x-labels.

2024-04-06 06:13 UTC, njzjz commented on doc/getting-started/quick_start.ipynb
> +    "</div>\n"
I merge it. It may be improved in a separated PR.

2024-04-06 07:06 UTC, merged