pt: support dpa2 model parallel inference
deepmodeling/deepmd-kit pull request #3657
Opened 2024-04-08 11:31 UTC by CaRoLZhangxy

2024-04-08 11:34 UTC, CaRoLZhangxy commented
TODO: add ut

2024-04-08 19:04 UTC, njzjz requested changes

2024-04-08 19:04 UTC, njzjz commented on source/op/pt/comm.cc
> +    using FPTYPE = double;
should be set to the type of g1

2024-04-08 19:04 UTC, njzjz commented on source/op/pt/comm.cc
> +          cudaMemcpy(recv_g1, send_g1, nrecv * tensor_size * sizeof(FPTYPE),
We may use [`gpuMemcpy`](https://docs.deepmodeling.com/projects/deepmd/en/latest/api_core/define_gpu__cuda_8h_1a4d7a4ae38c7a1fea58f92c95120471f2.html#define-gpumemcpy) to support both CUDA and ROCm.

2024-04-09 03:18 UTC, wanghan-iapcm commented on deepmd/pt/model/descriptor/dpa2.py
> +            g1 = g1_ext
really need this assignment?

2024-04-09 03:18 UTC, wanghan-iapcm commented on source/lib/include/neighbor_list.h
> +  InputNlist(int inum_,
it may not be a good idea to pack the communication part with the neighbor list. 
we need a new data class to store the communication information.

2024-04-09 03:18 UTC, wanghan-iapcm commented on source/op/pt/comm.cc
> +      const torch::Tensor& nghost_tensor) {
doc explaining the input variable is needed.

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
```suggestion
#ifdef GOOGLE_CUDA || TENSORFLOW_USE_ROCM
```

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
It might be a bit strange to use `GOOGLE_CUDA` and `TENSORFLOW_USE_ROCM` in the pytorch... but it's fine.

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
```suggestion
#ifdef GOOGLE_CUDA || TENSORFLOW_USE_ROCM
```

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
```suggestion
#ifdef GOOGLE_CUDA || TENSORFLOW_USE_ROCM
```

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
```suggestion
#ifdef GOOGLE_CUDA || TENSORFLOW_USE_ROCM
```

2024-04-21 08:15 UTC, njzjz commented on source/op/pt/comm.cc
> +#ifdef GOOGLE_CUDA
```suggestion
#ifdef GOOGLE_CUDA || TENSORFLOW_USE_ROCM
```

2024-04-23 21:23 UTC, njzjz commented on deepmd/pt/entrypoints/main.py
> +    if '"type": "dpa2"' in model.model_def_script:
should use an API instead of doing string searching

2024-04-25 07:39 UTC, njzjz commented on .github/workflows/test_cuda.yml
> +        python -m pytest -s -k "not test_lammps_dpa_pt.py" source/lmp/tests || (cat log.lammps && exit 1)
make pre-commit.ci pass
```suggestion
        python -m pytest -s -k "not test_lammps_dpa_pt.py" source/lmp/tests || (cat log.lammps && exit 1)
```

2024-04-25 18:29 UTC, njzjz commented on source/api_c/include/c_api.h
> +
@coderabbitai please generate function documentation according to `source/lib/include/neighbor_list.h`.

2024-04-25 18:33 UTC, njzjz commented on source/api_c/include/c_api.h
> +
Generate suggestion.

2024-04-25 18:53 UTC, njzjz commented on source/api_c/include/c_api.h
> +
@CaRoLZhangxy commit it if it is okay

2024-04-26 02:38 UTC, wanghan-iapcm requested changes

2024-04-26 02:38 UTC, wanghan-iapcm commented on deepmd/pt/model/descriptor/repformers.py
> +            assert extended_atype_embd is not None
```suggestion
            assert mapping is not None
            assert extended_atype_embd is not None
```

2024-04-26 02:38 UTC, wanghan-iapcm commented on source/api_cc/src/DeepPotPT.cc
> +  }
I would suggest using the metadata provide the key 
`metadata["message_passing"] = True/False`
to distinguish if the model needs to handle the communications. 

The reason to change the name of the key is to make the variable more self-explanatory. 

I also discourage the variable name `model_type`. I would suggest something like `do_message_passing`.

2024-04-26 05:24 UTC, njzjz commented on source/api_c/include/c_api.h
> +/*
comment should be written above the function. Here is for the function below

https://www.doxygen.nl/manual/docblocks.html

2024-04-26 19:27 UTC, njzjz commented on deepmd/pt/entrypoints/main.py
> +    if '"type": "dpa2"' in model.model_def_script:
@coderabbitai open an issue to track it

2024-04-26 19:27 UTC, njzjz approved these changes

2024-04-27 14:45 UTC, wanghan-iapcm approved these changes

2024-04-27 15:01 UTC, iProzd reviewed
Docstr of `comm_dict` missed in all the python classes.

2024-04-27 15:01 UTC, iProzd commented on deepmd/pt/model/atomic_model/base_atomic_model.py
> +        comm_dict: Optional[Dict[str, torch.Tensor]] = None,
docstr missed.

2024-04-28 06:52 UTC, iProzd approved these changes

2024-04-30 21:00 UTC, merged

2024-05-04 06:51 UTC, chazeon commented
I am unable to compile `comm.cc` after this pull request. The error I get is

```
-> % cmake --build . --parallel 8
[  3%] Built target deepmd_ipi
[  5%] Built target gtest
[ 19%] Built target deepmd
[ 20%] Built target gtest_main
[ 21%] Built target gmock
[ 22%] Built target gmock_main
[ 28%] Built target deepmd_cc_test_no_backend
[ 46%] Built target runUnitTests_lib
[ 52%] Built target deepmd_cc
[ 73%] Built target deepmd_op
[ 74%] Linking CXX shared module libdeepmd_op_pt.so
[ 76%] Built target deepmd_c
[ 88%] Built target runUnitTests_cc
[ 89%] Built target deepmd_gromacs
[ 90%] Built target dp_ipi
Undefined symbols for architecture arm64:
  "long* at::TensorBase::data_ptr<long>() const", referenced from:
      Border::unpack_communicator(at::Tensor const&, int&) in comm.cc.o
ld: symbol(s) not found for architecture arm64
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[ 99%] Built target runUnitTests_c
make[2]: *** [op/pt/CMakeFiles/deepmd_op_pt.dir/build.make:187: op/pt/libdeepmd_op_pt.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:549: op/pt/CMakeFiles/deepmd_op_pt.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

The error is related to these two lines:

https://github.com/CaRoLZhangxy/deepmd-kit/blob/beba142f64a51a9d6e65d6a621d30519679aa43d/source/op/pt/comm.cc#L323-L326

It seems `at::TensorBase::data_ptr<long>()` is not defined with `long`, but for `int`, `long long` etc in my `libtorch`.
I tried replacing `long int` with either `long long` or `int`. Both can be compiled.
Is there a specific reason why `long int` is used here?

```
-> % nm -gU libtorch_cpu.dylib | grep TensorBase | llvm-cxxfilt | grep ::data_ptr
0000000002153398 T c10::Float8_e5m2* at::TensorBase::data_ptr<c10::Float8_e5m2>() const
0000000002153524 T c10::Float8_e4m3fn* at::TensorBase::data_ptr<c10::Float8_e4m3fn>() const
0000000002152738 T c10::Half* at::TensorBase::data_ptr<c10::Half>() const
00000000021536b0 T c10::qint8* at::TensorBase::data_ptr<c10::qint8>() const
00000000021539c8 T c10::qint32* at::TensorBase::data_ptr<c10::qint32>() const
000000000215383c T c10::quint8* at::TensorBase::data_ptr<c10::quint8>() const
0000000002152bdc T c10::complex<c10::Half>* at::TensorBase::data_ptr<c10::complex<c10::Half>>() const
0000000002152ef4 T c10::complex<double>* at::TensorBase::data_ptr<c10::complex<double>>() const
0000000002152d68 T c10::complex<float>* at::TensorBase::data_ptr<c10::complex<float>>() const
000000000215320c T c10::BFloat16* at::TensorBase::data_ptr<c10::BFloat16>() const
0000000002153ce0 T c10::quint2x4* at::TensorBase::data_ptr<c10::quint2x4>() const
0000000002153b54 T c10::quint4x2* at::TensorBase::data_ptr<c10::quint4x2>() const
0000000002152108 T signed char* at::TensorBase::data_ptr<signed char>() const
0000000002153080 T bool* at::TensorBase::data_ptr<bool>() const
0000000002152a50 T double* at::TensorBase::data_ptr<double>() const
00000000021528c4 T float* at::TensorBase::data_ptr<float>() const
0000000002151f7c T unsigned char* at::TensorBase::data_ptr<unsigned char>() const
0000000002152420 T int* at::TensorBase::data_ptr<int>() const
0000000002152294 T short* at::TensorBase::data_ptr<short>() const
00000000021525ac T long long* at::TensorBase::data_ptr<long long>() const
```

My environment is:

```
     active environment : deepmd-dev
    active env location : /Users/chazeon/miniforge3/envs/deepmd-dev
            shell level : 1
       user config file : /Users/chazeon/.condarc
 populated config files : /Users/chazeon/miniforge3/.condarc
                          /Users/chazeon/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=arm64
                          __osx=14.4.1=0
                          __unix=0=0
       base environment : /Users/chazeon/miniforge3  (writable)
      conda av data dir : /Users/chazeon/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/chazeon/miniforge3/pkgs
                          /Users/chazeon/.conda/pkgs
       envs directories : /Users/chazeon/miniforge3/envs
                          /Users/chazeon/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Darwin/23.4.0 OSX/14.4.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
This might related to: https://stackoverflow.com/questions/67584843/pytorch-tensordata-ptrlong-long-not-working-on-linux

2024-05-04 07:24 UTC, njzjz commented
@chazeon could you send a PR?

In a 64-bit system, `long` and `long long` have the same size, which might be why `long` can be compiled on Linux. But it looks dangerous.

2024-05-04 07:46 UTC, njzjz commented
`long` used here also requires to be reviewed:

https://github.com/deepmodeling/deepmd-kit/blob/ebd809b56798a268d6048c056cdf27e0c55b09ce/source/api_cc/src/DeepPotPT.cc#L199-L213