convert dp1.2 model to dp1.3 model
deepmodeling/deepmd-kit pull request #369
Opened 2021-02-18 22:36 UTC by denghuilu

2021-02-20 08:18 UTC, amcadmus requested changes
The file name `convert.py` should be changed to e.g. `convet_to_13.py`

2021-02-21 03:45 UTC, njzjz commented
It is strange to push this commit to `r1.2`... Why not push to `r1.3` and call it `convert_from_12`?

2021-02-21 06:26 UTC, amcadmus commented
> It is strange to push this commit to `r1.2`... Why not push to `r1.3` and call it `convert_from_12`?

The 1.2 environment is needed to load the 1.2 model.

2021-02-21 06:40 UTC, amcadmus approved these changes

2021-02-21 06:40 UTC, merged