Add paddle backend core and water se e2 a
deepmodeling/deepmd-kit pull request #4302
Opened 2024-11-03 07:45 UTC by HydrogenSulfate

Split <https://github.com/deepmodeling/deepmd-kit/pull/4157> into several pull requests.

1. Add core modules of paddle backend(`deepmd.pd.*`) and related backend module unitests.
2. Support training/testing/freeze(C++ inference will be supported in subsequent pull request) for example water/se_e2_a.
3. Add se_e2_a related uinttests

2024-11-03 10:43 UTC, HydrogenSulfate commented
Hello @njzjz , I have a question about the naming of the functions `serialize_from_file` and `deserialize_to_file`. According to the docstring explanations for these two functions and the general meaning of "serialize," why can't these functions be named `serialize_to_file` and `deserialize_from_file` instead? I was confused when I first saw these two functions.

2024-11-04 23:20 UTC, njzjz commented
> Hello @njzjz , I have a question about the naming of the functions `serialize_from_file` and `deserialize_to_file`. According to the docstring explanations for these two functions and the general meaning of "serialize," why can't these functions be named `serialize_to_file` and `deserialize_from_file` instead? I was confused when I first saw these two functions.

Do you mean `serialize_hook` and `deserialize_hook`?

https://insiders.vscode.dev/github/deepmodeling/deepmd-kit/blob/devel/deepmd/backend/backend.py#L179-L202

2024-11-06 22:33 UTC, njzjz commented
> Attention: Patch coverage is `55.25965%` with `2016 lines` in your changes missing coverage. Please review.

About 2000+ lines have yet to be tested in the CI. Could you take a look at the coverage report?

2024-11-06 22:34 UTC, njzjz commented on deepmd/pd/utils/ase_calc.py
A simple redirect can be removed. The PyTorch backend has it due to historical reasons, but for a new backend, it is not required.

2024-11-07 03:21 UTC, HydrogenSulfate commented on deepmd/pd/utils/ase_calc.py
> A simple redirect can be removed. The PyTorch backend has it due to historical reasons, but for a new backend, it is not required.

Thanks for reply, this file seems not used in water.

2024-11-07 03:22 UTC, HydrogenSulfate commented
> > Attention: Patch coverage is `55.25965%` with `2016 lines` in your changes missing coverage. Please review.
> 
> About 2000+ lines have yet to be tested in the CI. Could you take a look at the coverage report?



> > Attention: Patch coverage is `55.25965%` with `2016 lines` in your changes missing coverage. Please review.
> 
> About 2000+ lines have yet to be tested in the CI. Could you take a look at the coverage report?

Thanks, I will check it out and remove code not used in water.

2024-11-11 23:58 UTC, njzjz commented
It seems to me that Paddle has a conflict cuDNN with JAX. It's hard to maintain the CUDA things for multiple software...

2024-11-12 10:57 UTC, HydrogenSulfate commented
@njzjz hello, I found the issue lies with the nvidia-cuda-xxx series dependencies when the Paddle framework is installed, which have a unilateral impact on JAX. However, in the environment that JAX depends on, Paddle can works well. Therefore, my solution is to first install PaddlePaddle in the `test_cuda.yml` file, and then install JAX, Torch, and other packages. This way, the Paddle dependencies won't affect the other dependencies.

2024-11-14 20:44 UTC, njzjz requested changes
I have some additional comments. We can merge this PR after v3.0.0 is released and the r3.0 branch is checked out.

2024-11-14 20:44 UTC, njzjz commented on deepmd/pd/cxx_op.py
> +    # NOTE: Paddle do not support loading library from .so file yet.
I am wondering whether this method will be used in the future? In fact, if no C++ codes are built, there is no need to change `backend` directory.

2024-11-14 20:44 UTC, njzjz commented on deepmd/pd/utils/cache.py
This file can be remove if it is not used.

2024-11-14 20:44 UTC, njzjz commented on deepmd/pd/utils/learning_rate.py
This file can be removed and the redirected method can be used directly.

2024-11-14 20:44 UTC, njzjz commented on deepmd/pd/utils/plugin.py
This file can be removed and the redirected method can be used directly.

2024-11-14 20:44 UTC, njzjz commented on source/tests/pd/requirements.txt
This file can be removed.

2024-11-15 04:46 UTC, HydrogenSulfate commented
> I have some additional comments. We can merge this PR after v3.0.0 is released and the r3.0 branch is checked out.

Thanks for the comments, redundant files&codes were removed.

2024-11-15 18:32 UTC, njzjz approved these changes

2024-11-23 03:55 UTC, iProzd approved these changes

2024-11-25 07:28 UTC, njzjz commented
@coderabbitai resolve

2024-11-25 07:34 UTC, njzjz commented
@coderabbitai resolve

2024-11-25 07:42 UTC, njzjz commented on deepmd/pd/infer/inference.py
> +        model_params = state_dict["_extra_state"]["model_params"]
@coderabbitai resolve

2024-11-25 07:51 UTC, njzjz commented
> @coderabbitai resolve

... It seems to be not working. The comments may be required to be manually resolved

2024-11-27 05:23 UTC, HydrogenSulfate commented
> @HydrogenSulfate A segfault appears in the GPU test. https://github.com/deepmodeling/deepmd-kit/actions/runs/12005580706/job/33462440790

I have make a new environment with cuda11.8 and installed the nightly build paddle(`3.0.0.dev20241126`), but all paddle tests running successfully as below.

``` shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

![image](https://github.com/user-attachments/assets/ad35ea12-f738-4055-b3b1-426721765994)

It seems a weird issue...

2024-11-27 06:17 UTC, njzjz commented
> It seems a weird issue and is there any way to get the detailed error log from Test CUDA?

It's run in a docker container, so I think it may be reproducible.

Btw, the image is nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

2024-11-27 06:46 UTC, njzjz commented
A bit strange, but the segfault disappeared.

2024-11-27 08:37 UTC, HydrogenSulfate commented
> > It seems a weird issue and is there any way to get the detailed error log from Test CUDA?
> 
> It's run in a docker container, so I think it may be reproducible.
> 
> Btw, the image is nvidia/cuda:12.6.2-cudnn-devel-ubuntu22.04

If we can add -v or -vv to pytest's argument so the test log can be a bit more detailed(but might not clear enough...)

2024-11-27 10:23 UTC, merged