Adding entries in document
deepmodeling/deepmd-kit pull request #468
Opened 2021-04-02 03:12 UTC by tuoping

New file: novel-auxiliary-options.md, application-examples.md
Add the unit and sequence order of virial in use-deepmd-kit.md
Add hardware-platforms in install.md

2021-04-02 04:43 UTC, amcadmus requested changes

2021-04-02 04:43 UTC, amcadmus commented on doc/use-deepmd-kit.md
> +Virial  | kBar
The unit of virial is eV.

2021-04-02 05:08 UTC, njzjz commented
CI build error is related to https://github.com/actions/virtual-environments/issues/2950

2021-04-02 05:15 UTC, njzjz commented on doc/use-deepmd-kit.md
> -This `force.raw` contains 3 frames with each frame having the forces of 2 atoms, thus it has 3 lines and 6 columns. Each line provides all the 3 force components of 2 atoms in 1 frame. The first thre
Can you make sure it’s in this order…

2021-04-02 05:16 UTC, njzjz commented on doc/use-deepmd-kit.md
> +This `force.raw` contains 3 frames with each frame having the forces of 2 atoms, thus it has 3 lines and 6 columns. Each line provides all the 3 force components of 2 atoms in 1 frame. The first thre
Can you make sure it’s in this order…

2021-04-02 06:18 UTC, amcadmus commented on doc/use-deepmd-kit.md
> +This `force.raw` contains 3 frames with each frame having the forces of 2 atoms, thus it has 3 lines and 6 columns. Each line provides all the 3 force components of 2 atoms in 1 frame. The first thre
the order should be xx xy xz yx yy yz zx zy zz

2021-04-02 06:58 UTC, tuoping commented on doc/use-deepmd-kit.md
> +This `force.raw` contains 3 frames with each frame having the forces of 2 atoms, thus it has 3 lines and 6 columns. Each line provides all the 3 force components of 2 atoms in 1 frame. The first thre
![捕获](https://user-images.githubusercontent.com/80671886/113390218-de27fb00-93c3-11eb-9d5f-8da6132da807.PNG)

2021-04-02 07:00 UTC, tuoping commented on doc/use-deepmd-kit.md
> +This `force.raw` contains 3 frames with each frame having the forces of 2 atoms, thus it has 3 lines and 6 columns. Each line provides all the 3 force components of 2 atoms in 1 frame. The first thre
这是dpdata里边的，判断错误，sorry。

2021-04-02 07:42 UTC, tuoping commented on doc/use-deepmd-kit.md
> +Virial  | kBar
The virial in VASP OUTCAR is provided with both units, eV and kB, and dpdata took the ones with unit kB.

2021-04-02 07:43 UTC, tuoping commented on doc/use-deepmd-kit.md
> +Virial  | kBar
![捕获](https://user-images.githubusercontent.com/80671886/113394081-38c45580-93ca-11eb-9fee-72ff17ab97f5.PNG)

2021-04-02 08:51 UTC, tuoping commented
Please fix this bug with compling.

2021-04-02 09:55 UTC, amcadmus commented on doc/use-deepmd-kit.md
> +Virial  | kBar
The virial is scaled to eV, see https://github.com/deepmodeling/dpdata/blob/cf4c99bdfdd938176c37f0910d0bd90b45c5dc77/dpdata/system.py#L1151

2021-04-02 18:46 UTC, njzjz commented
> Please fix this bug with compling.

fixed in https://github.com/deepmodeling/deepmd-kit/commit/e1119de1cf09fb1365fec29c9690f63d4e4436fb

2021-04-05 07:51 UTC, tuoping commented on doc/use-deepmd-kit.md
> +Virial  | kBar
Got it. Thank you.

2021-04-05 08:39 UTC, amcadmus approved these changes

2021-04-05 23:54 UTC, merged