fix issue 658
deepmodeling/deepmd-kit pull request #754
Opened 2021-06-16 08:50 UTC by denghuilu

### changes

- add support for exclude_types model.

2021-06-16 08:51 UTC, denghuilu commented
#658 should be fixed now.

2021-06-16 16:43 UTC, njzjz requested changes

2021-06-16 16:43 UTC, njzjz commented on deepmd/utils/tabulate.py
> +                 exclude_types : List[int] = []) -> None:
```suggestion
                 exclude_types : List[List[int]] = []) -> None:
```

2021-06-16 16:43 UTC, njzjz commented on deepmd/utils/tabulate.py
> +        exclude_types : list[int]
```suggestion
        exclude_types : list[list[int]]
```

2021-06-17 10:42 UTC, njzjz approved these changes

2021-06-17 12:43 UTC, njzjz commented on deepmd/utils/tabulate.py
> +            if self.type_one_side or ((int(ii / self.ntypes), int(ii % self.ntypes)) not in self.exclude_types):
In fact you can use `ii // self.ntypes` other than `int(ii / self.ntypes)`.

2021-06-18 16:11 UTC, njzjz approved these changes

2021-06-19 09:40 UTC, merged