add type-embedding developer doc
deepmodeling/deepmd-kit pull request #762
Opened 2021-06-17 02:40 UTC by tuoping

Copied from wiki. #753

2021-06-17 06:00 UTC, amcadmus reviewed
It is better to ref to the development doc in `train-se-e2-a-tebd.md`

2021-06-17 08:31 UTC, tuoping commented
Should we add a link to `train-se-e2-a-tebd.md` in getting-started.md?

2021-06-17 10:37 UTC, njzjz requested changes

2021-06-17 10:37 UTC, njzjz commented on doc/development/type-embedding.md
> +A detailed introduction can be found at [`se_e2_a_tebd`](https://github.com/deepmodeling/deepmd-kit/blob/v2.0.0.b1/doc/train-se-e2-a-tebd.md). Looking for a fast start up, you can simply add a `type_
Could you use the relative link here?

2021-06-18 00:20 UTC, njzjz approved these changes

2021-06-18 14:36 UTC, jxxiaoshaoye approved these changes

2021-06-19 09:39 UTC, merged