speed up format_nlist_b
deepmodeling/deepmd-kit pull request #832
Opened 2021-07-07 02:57 UTC by BaoHhhhhan

This PR works on  optimizing ROCm function format_nlist_b.

In the previous work, one thread in a thread block handles all neighbors of one center atom. therefore, the parallel granularity is coarse. Besides, Threads in a thread block access memory which is not coalesced.

A straightforward way is to make threads in a block handle a part of  neighbors of a center atom. Before doing this, we have to do a preprocession on nei_iter array, which doesn't take too much time. In our benchmark, this optimization gets ≈7x speed up.

We also benchmark the E2E performance on LAMMPS inference. On compressed copper model, this work gets ≈1.05x speedup on pairs computing.

Baseline:
[hcctrace.out.before.json.zip](https://github.com/deepmodeling/deepmd-kit/files/6773890/hcctrace.out.before.json.zip)
![profiling_before](https://user-images.githubusercontent.com/44225751/124691133-e4bb9680-df0d-11eb-8e6e-ef08d9daee85.jpg)

After speedup:
[hcctrace.out.after.json.zip](https://github.com/deepmodeling/deepmd-kit/files/6773892/hcctrace.out.after.json.zip)
![profiling_after](https://user-images.githubusercontent.com/44225751/124691115-dd948880-df0d-11eb-9793-86faa54361d2.jpg)

2021-07-09 02:36 UTC, denghuilu commented
@BaoHhhhhan Have tested the UTs in source/lib/tests and source/api_cc/tests?

2021-07-09 02:44 UTC, BaoHhhhhan commented
&nbsp; Sorry, I forgot testing. I will test it later.





------------------ Original ------------------
From: Denghui Lu ***@***.***&gt;
Date: Fri,Jul 9,2021 10:36 AM
To: deepmodeling/deepmd-kit ***@***.***&gt;
Cc: baohan ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [deepmodeling/deepmd-kit] speed up format_nlist_b (#832)





 
@BaoHhhhhan Have you tested the UTs in source/lib/tests and source/api_cc/tests?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-09 04:34 UTC, denghuilu requested changes

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  int row = blockIdx.y;
```suggestion
  int row = blockIdx.x;
```

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  int col = blockIdx.x * blockDim.x + threadIdx.x;
```suggestion
  int col = blockIdx.y * blockDim.x + threadIdx.x;
```

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  int row = blockIdx.y;
```suggestion
  int row = blockIdx.x;
```

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  int col = blockIdx.x * blockDim.x + threadIdx.x;
```suggestion
  int col = blockIdx.y * blockDim.x + threadIdx.x;
```

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  hipLaunchKernelGGL(fill_nei_iter, dim3((max_nbor_size + LEN - 1) / LEN, nloc) , LEN, 0, 0,
```suggestion
  hipLaunchKernelGGL(fill_nei_iter, dim3(nloc, (max_nbor_size + LEN - 1) / LEN) , LEN, 0, 0,
```

2021-07-09 04:34 UTC, denghuilu commented on source/lib/src/rocm/prod_env_mat.hip.cu
> +  hipLaunchKernelGGL(format_nlist_fill_b, dim3((max_nbor_size + LEN - 1) / LEN, nloc), LEN, 0, 0,
```suggestion
  hipLaunchKernelGGL(format_nlist_fill_b, dim3(nloc, (max_nbor_size + LEN - 1) / LEN), LEN, 0, 0, 
```

2021-07-09 06:22 UTC, pkulzy commented
I have done UT tests and there is no problem, and accelerated by a factor of seven

2021-07-09 06:22 UTC, pkulzy approved these changes

2021-07-09 06:56 UTC, denghuilu commented
@BaoHhhhhan we cannot use nloc as the blockIdx.y,  please review my suggestions.

2021-07-09 14:15 UTC, amcadmus commented
> @BaoHhhhhan we cannot use nloc as the blockIdx.y, please review my suggestions.

I am wondering why the bugs were not detected by our UTs? Are the UTs incomplete?

2021-07-09 18:08 UTC, pkulzy commented
> I have done UT tests and there is no problem, and accelerated by a factor of seven

I ran all the UT test again. And found in the API - cc UT, there will be two test not through TestInferDeepPolarNew cpu_build_nlist and TestInferDeepPolarNew.cpu_lmp_nlist. There may be some places that need to be modified according to @amcadmus's  opinions. I'm really sorry for my mistakes in my work.

2021-07-10 14:54 UTC, amcadmus approved these changes

2021-07-11 06:48 UTC, denghuilu approved these changes

2021-07-11 12:01 UTC, merged

2021-07-12 03:23 UTC, denghuilu commented
> > @BaoHhhhhan we cannot use nloc as the blockIdx.y, please review my suggestions.
> 
> I am wondering why the bugs were not detected by our UTs? Are the UTs incomplete?

To detect the blockIdx.y bug in UT, we need nloc >= 65536. So previous UT didn't cover it.