Passing error to TF instead of exit
deepmodeling/deepmd-kit pull request #918
Opened 2021-08-04 04:06 UTC by njzjz

This commit does three little things:
(1) create an exception called `deepmd::deepmd_exception` (based on `std::runtime_error`);
(2) throw this exception instead of `exit` or `std::runtime_error`;
(3) catch this exception in the op, and pass to TF using `OP_REQUIRES_OK`.
One more, the OOM error will raise ResourceExhausted, as the same as TF ops.

The benifit of doing so is that the TF side and Python side can processing other things, catch the error, and print the traceback.
This commit can also fix #802, where the Python didn't save the buffer to the file before exit.

2021-08-04 07:28 UTC, amcadmus requested changes
We should avoid copying the `try ... catch ...` in all OP implementations. 

Shall we define some function like 
```cc
#define void ComputeFunction(OpKernelContext* context);

void save_compute(OpKernelContext* context, const ComputeFunction &ff) {
  try{
    ff(context);
  } catch (...) {
    ....
  } catch (...) {
    ....
  }
}
```
where `ComputeFunction` is the implementation of the OP.

2021-08-04 09:27 UTC, njzjz commented
See https://github.com/deepmodeling/deepmd-kit/blob/9c8a0da4a91b8d060be312cafa82c379ccc8fc37/source/op/custom_op.cc#L4-L20 and https://github.com/deepmodeling/deepmd-kit/blob/9c8a0da4a91b8d060be312cafa82c379ccc8fc37/source/op/descrpt.cc#L52-L56

2021-08-04 10:58 UTC, amcadmus commented
> https://github.com/deepmodeling/deepmd-kit/blob/9c8a0da4a91b8d060be312cafa82c379ccc8fc37/source/op/custom_op.cc#L5-L5
> 

The name should have been `safe_compute`, sry my mistake

2021-08-04 23:34 UTC, amcadmus approved these changes

2021-08-06 01:50 UTC, denghuilu approved these changes

2021-08-06 05:51 UTC, pkulzy approved these changes
There is no problem on ROCm platform about UT and compiling

2021-08-06 13:32 UTC, merged